export const plans = [
  {
    plan: "Free",
    month: "0",
    features: [
      "Up to 50 Clients",
      "Up to 25 Active Loans",
      "Up to 100 Total Loan Records",
      "20 Reminders per Month",
      "Basic Loan Tracking & Installments",
      "Client Management",
      "Standard Support",
    ],
    title: "Start managing your loans with zero cost",
  },
  {
    plan: "Pro",
    month: "14.99",
    features: [
      "Up to 1,000 Clients",
      "Up to 200 Active Loans",
      "Up to 5,000 Total Loan Records",
      "300 Reminders per Month",
      "Advanced Loan Calculations",
      "Export Data (CSV/PDF)",
      "Buy Additional Reminders",
      "Priority Support",
    ],
    title: "Everything you need to run a growing lending business",
  },
  {
    plan: "Business",
    month: "59.99",
    features: [
      "Unlimited Clients",
      "Up to 1,000 Active Loans",
      "Up to 50,000 Total Loan Records",
      "2,000 Reminders per Month",
      "Advanced Analytics & Insights",
      "Full Data Export & Backup",
      "Buy Additional Reminders",
      "Priority Support",
    ],
    title: "High-capacity tools for large and scaling lending operations",
  },
];
