export const plans = [
  {
    plan: "Free",
    day: "0",
    month: "0",
    recurring: "/forever",
    features: [
      "Up to 5 Clients",
      "Up to 10 Accounts (Loans or Invoices)",
      "Basic Dashboard",
      "Manual Installment Tracking",
      "Record Payments",
      "Email Support",
    ],
    title:
      "Perfect for individuals getting started with tracking client payments.",
  },
  {
    plan: "Pro",
    day: "0.49",
    month: "14.85",
    recurring: "/day",
    features: [
      "Up to 50 Clients",
      "Up to 100 Accounts (Loans & Invoices)",
      "Installment Scheduling",
      "Payment Tracking & History",
      "Generate Invoice PDF",
      "Download Reports (Excel)",
      "Manual Reminders (Email)",
      "Basic Dashboard Insights",
      "Priority Email Support",
    ],
    title:
      "For freelancers and small businesses managing client payments and invoices.",
  },
  {
    plan: "Business",
    day: "1.65",
    month: "49.65",
    recurring: "/day",
    features: [
      "Unlimited Clients",
      "Unlimited Accounts (Loans & Invoices)",
      "Automatic Payment Reminders",
      "WhatsApp Reminders",
      "Advanced Dashboard & Analytics",
      "Overdue & Due Tracking",
      "Client Statements (Downloadable)",
      "Up to 5 Team Members",
      "Faster Support",
    ],
    title:
      "For growing businesses that need automation and better control over receivables.",
  },
  {
    plan: "Enterprise",
    day: "7.29",
    month: "218.85",
    recurring: "/day",
    features: [
      "Everything in Business",
      "Unlimited Team Members",
      "API Access",
      "Custom Integrations",
      "Dedicated Support",
      "Priority Performance",
      "Custom Reports",
    ],
    title: "For large businesses managing high-volume clients and payments.",
  },
];
